创建向量/矩阵

In [17]:
import numpy as np

vec = np.array([0.1,0.2,0.3])
print(f"向量:{vec}")
print(f"形状:{vec.shape}")

mat = np.array([
    [0.1,0.2,0.3],
    [0.4,0.5,0.6]
])
print(f"矩阵:{mat}")
print(f"形状:{mat.shape}")

向量:[0.1 0.2 0.3]
形状:(3,)
矩阵:[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]
形状:(2, 3)


增删向量

In [2]:
import numpy as np

vec = np.array([0.1,0.2,0.3])

vec1 = np.array([vec,[0.4,0.5,0.6]])
print(f"矩阵:{vec1}，形状:{vec1.shape}")

# 删除索引为2的元素（即0.3）
vec2 = np.delete(vec, 2)
print(f"向量:{vec2}，形状:{vec2.shape}")
# 删除多个元素（索引1和2）
vec3 = np.delete(vec, [1, 2])
print(f"向量:{vec3}，形状:{vec3.shape}")

矩阵:[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]，形状:(2, 3)
向量:[0.1 0.2]，形状:(2,)
向量:[0.1]，形状:(1,)


增加纬度

In [22]:
import numpy as np

vec = np.array([0.1,0.2,0.3])
print(f"向量:{vec}")
print(f"形状:{vec.shape}")

# 显式增加
vec1 = vec.reshape(3,1)
print(f"向量:{vec1}")
print(f"形状:{vec1.shape}")

vec2 = vec.reshape(1,3)
print(f"向量:{vec2}")
print(f"形状:{vec2.shape}")

# 通过新增轴实现维度扩展
vec3 = vec[:,np.newaxis]
print(f"向量:{vec3}")
print(f"形状:{vec3.shape}")

vec4 = vec[np.newaxis,:]
print(f"向量:{vec4}")
print(f"形状:{vec4.shape}")

向量:[0.1 0.2 0.3]
形状:(3,)
向量:[[0.1]
 [0.2]
 [0.3]]
形状:(3, 1)
向量:[[0.1 0.2 0.3]]
形状:(1, 3)
向量:[[0.1]
 [0.2]
 [0.3]]
形状:(3, 1)
向量:[[0.1 0.2 0.3]]
形状:(1, 3)


矩阵乘法

In [27]:
import numpy as np

# 状态 (State)
state = np.array([2, 1])

# 权重 (Weights)
weights = np.array([0.5, 0.8])

# 错误做法：逐元素相乘 (得到的是 [1.0, 0.8]，不是一个总分)
print(state * weights) 

# 正确做法：点积 (Dot Product)
# 计算过程: 2*0.5 + 1*0.8 = 1.0 + 0.8 = 1.8
score = np.dot(state, weights) 
# 或者写成更现代的写法：
score_v2 = state @ weights 

print(f"当前得分: {score}") # 输出 1.8

[1.  0.8]
当前得分: 1.8


随机

In [31]:
import numpy as np

actions = ['向左', '向右', '不动']
probs = [0.1, 0.1, 0.8]  # 概率分布：大部分时候不动

# 模拟 10 次动作选择
for i in range(10):
    # p=probs 表示按照我们指定的概率来选
    action = np.random.choice(actions, p=probs)
    print(f"第 {i} 步采取动作: {action}")

第 0 步采取动作: 向左
第 1 步采取动作: 不动
第 2 步采取动作: 不动
第 3 步采取动作: 不动
第 4 步采取动作: 不动
第 5 步采取动作: 不动
第 6 步采取动作: 不动
第 7 步采取动作: 不动
第 8 步采取动作: 不动
第 9 步采取动作: 向右


掩码与过滤

In [5]:
import numpy as np

# 创建一个5*5的随机矩阵
mat = np.random.rand(5, 5)
print(f"矩阵:{mat}")

# 2. 生成“掩码” (Mask)
# 这步会生成一个全是 True/False 的矩阵(小于0.5的为true)
mask = mat < 0.5
print(f"掩码:{mask}")

# 3. 利用掩码修改数据
# 意思就是：把 mask 为 True 对应位置的 data 值设为 0
mat[mask] = 0
print(f"处理后:{mat}")


矩阵:[[0.22410679 0.41634676 0.75548964 0.06561463 0.8135529 ]
 [0.97104329 0.44134845 0.16395005 0.96953016 0.59790451]
 [0.55063841 0.01766841 0.23311938 0.86865414 0.19917138]
 [0.16138482 0.11456451 0.27403917 0.06413512 0.61271081]
 [0.5620541  0.75292909 0.01685571 0.78766195 0.70962219]]
掩码:[[ True  True False  True False]
 [False  True  True False False]
 [False  True  True False  True]
 [ True  True  True  True False]
 [False False  True False False]]
处理后:[[0.         0.         0.75548964 0.         0.8135529 ]
 [0.97104329 0.         0.         0.96953016 0.59790451]
 [0.55063841 0.         0.         0.86865414 0.        ]
 [0.         0.         0.         0.         0.61271081]
 [0.5620541  0.75292909 0.         0.78766195 0.70962219]]


exercise

In [27]:
import numpy as np

# 1、
vec = np.array([0.1,0.2,0.3])
print(f"{vec.shape}")
vec1 = np.array([[0.1,0.2,0.3]])
print(f"{vec1.shape}")
vec2 = np.array([[0.1],[0.2],[0.3]])
print(f"{vec2.shape}")

vec3 = vec.reshape(1,3)
print(f"{vec3.shape}")
vec4 = vec.reshape(3,1)
print(f"{vec4.shape}")

vec5 = vec[np.newaxis,:]
print(f"{vec5.shape}")
vec6 = vec[:,np.newaxis]
print(f"{vec6.shape}")

# 2、
state = np.array([
    [0.1,0.2,0.3],
    [0.4,0.5,0.6]
])
weights = np.array([2,2,2])
weights_ = weights.reshape(3,1)

score = np.dot(state,weights_)
score_ = state @ weights_

print(f"score:{score}\nscore_:{score_}")

# 3、
actions = np.array([0,1,2,3])
probs = np.array([0.1,0.7,0.1,0.1])

action = np.random.choice(actions, p=probs, size=10)
print(f"{action}")

# 4、
mat_data = np.random.rand(5, 5)
print(f"原始数据:{mat_data}")

mask1 = mat_data > 0.8
mask2 = mat_data < 0.3
mat_data[mask1] = 1
mat_data[mask2] = -1

print(f"处理后:{mat_data}")

(3,)
(1, 3)
(3, 1)
(1, 3)
(3, 1)
(1, 3)
(3, 1)
score:[[1.2]
 [3. ]]
score_:[[1.2]
 [3. ]]
[1 0 1 1 0 1 0 0 1 1]
原始数据:[[0.61833293 0.59213768 0.12411875 0.29757546 0.29360756]
 [0.53983929 0.9011506  0.32184819 0.09130314 0.03096947]
 [0.05369344 0.04981575 0.23996519 0.02668344 0.5425723 ]
 [0.01439437 0.71135995 0.80642691 0.19817796 0.17929809]
 [0.6619489  0.85261316 0.42106217 0.96359858 0.05636405]]
处理后:[[ 0.61833293  0.59213768 -1.         -1.         -1.        ]
 [ 0.53983929  1.          0.32184819 -1.         -1.        ]
 [-1.         -1.         -1.         -1.          0.5425723 ]
 [-1.          0.71135995  1.         -1.         -1.        ]
 [ 0.6619489   1.          0.42106217  1.         -1.        ]]
